// Supabase Edge Function: POST /match — thin Deno wrapper around the SAME
// deterministic engine the app bundles (spec §4 / plan decision 2). Deploy is
// Phase 2; see deps.md for the bundling step that produces engine.bundle.js.
//
// deno-lint-ignore-file no-explicit-any
import { z } from 'npm:zod@4';
// Generated by: npx esbuild src/engine/index.ts --bundle --format=esm --alias:@=./src --outfile=supabase/functions/match/engine.bundle.js
import { runMatch } from './engine.bundle.js';

const profileSchema = z.object({
  units: z.enum(['metric', 'imperial']),
  region: z.enum(['UK', 'US']),
  sex: z.enum(['M', 'F', 'NA']),
  age: z.number().min(13).max(95),
  weightKg: z.number().min(35).max(180),
  weeklyKm: z.number().min(0).max(300),
  easyPaceSecPerKm: z.number().optional(),
  race: z.object({ distanceKm: z.number().positive(), timeSec: z.number().positive() }).optional(),
  experience: z.enum(['new', 'regular', 'high']),
  mode: z.enum(['single', 'rotation']),
  primaryIntent: z.enum(['race', 'tempo', 'daily', 'recovery', 'everything']),
  raceDistanceTargetKm: z.union([z.literal(5), z.literal(10), z.literal(21.1), z.literal(42.2)]).optional(),
  budget: z.object({
    type: z.enum(['perShoe', 'total']),
    amountGbp: z.number().min(50),
    stretch: z.boolean(),
  }),
  brandBlocks: z.array(z.string()),
  brandLoves: z.array(z.string()),
  fit: z.object({ wide: z.boolean(), roomyToe: z.boolean() }),
  wantsStability: z.boolean(),
  injuryFlags: z.array(z.enum(['bone_stress', 'achilles_calf', 'knee', 'plantar'])),
  currentShoeSlug: z.string().optional(),
  currentShoeVerdict: z.enum(['love', 'meh', 'hate']).optional(),
});

const cors = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors });
  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'POST only' }), { status: 405, headers: cors });
  }
  try {
    const body = await req.json();
    const profile = profileSchema.parse(body);
    const result = runMatch(profile as any);
    return new Response(JSON.stringify(result), {
      headers: { ...cors, 'Content-Type': 'application/json' },
    });
  } catch (e) {
    const message = e instanceof z.ZodError ? e.issues : String(e);
    return new Response(JSON.stringify({ error: message }), {
      status: 400,
      headers: { ...cors, 'Content-Type': 'application/json' },
    });
  }
});
