/**
 * AI-cut (rembg/U2Net) transparent product images, generated by
 * scripts/cut-images.py from official brand sources. Bundled locally so the
 * preview never depends on hotlink behaviour. Same preview-only legal stance
 * as devImages — licensed feed imagery replaces these at launch.
 */
export const LOCAL_SHOE_IMAGES: Record<string, number> = {
  'adidas-adizero-evo-sl': require('../../assets/shoes/adidas-adizero-evo-sl.png'),
  'adidas-adios-pro-4': require('../../assets/shoes/adidas-adios-pro-4.png'),
  'hoka-bondi-9': require('../../assets/shoes/hoka-bondi-9.png'),
  'saucony-endorphin-speed-5': require('../../assets/shoes/saucony-endorphin-speed-5.png'),
};
